### ISSUE TITLE
Redirects not working

### ISSUE THREAD

**Issue by ulyanuha** [segy/Mpdf#1]
Thank you for this great component!
I ran into issue that redirects in controller which uses this component do not work. I am talking about $this->redirect(url) method

**Comment by segy** [comment]
Hello. Can you please provide some example / the error message? I tried redirect in a method of controller that uses this component (and also a redirect after calling $this->Mpdf->init()) and it works as expected. Thank you.

**Comment by ulyanuha** [comment]
There is no error message just redirects are not working, though standart php redirects using header() function are working fine. When I have removed mpdf from the components list - redirects worked fine. Maybe you can't get this error because cakePHP I am using is not last version, it is 2 years old project. CakePHP version 1.3.0-RC4

**Comment by segy** [comment]
I'm sorry but class is for CakePHP 2.x. I am sure you will be able to modify it for older version to work with redirects. I added readme to this project so requirements will be clear now hopefully.
