### ISSUE TITLE
Missing Plugin

### ISSUE THREAD

**Issue by carloskire** [segy/Mpdf#6]
Hi. There is a closed issue with this same problem:

Missing Plugin

Error: The application is trying to load a file from the Mpdf plugin

Error: Make sure your plugin Mpdf is in the app/Plugin directory and was loaded

<?php
CakePlugin::load('Mpdf');

Please note cake docum says 
New for CakePHP 2.0, plugins need to be loaded manually in app/Config/bootstrap.php.

Also, the downloaded folder is called Mpdf-master; should it be renamed to Mpdf?

Please help.

Carlos

**Comment by segy** [comment]
Hello. 

You are right. You have to load the plugin manually. And the mpdf should be placed in your Vendor folder mpdf.

Let me know if this fixes your issues

segy

**Comment by joashp** [comment]
Hi segy, 
I am facing this similar issue. I have added CakePlugin::load('Mpdf');
in app/Config/bootstrap.php

What do I need to add in Plugins folder?

**Comment by segy** [comment]
Hello. You need to have mpdf in your vendor folder. So download it from http://www.mpdf1.com/mpdf/index.php?page=Download and copy it to your vendor folder

**Comment by joashp** [comment]
I did that. But still was getting same issue, so i copied in plugins folder too. 
Now, I am facing this issue. Can you please help me, I am new to Cakephp and can you create a demo project with the plugin and send me if possible.

Missing Component

Error: Mpdf.MpdfComponent could not be found.

Error: Create the class MpdfComponent below in file: D:\project_www\app\Plugin\Mpdf\Controller\Component\MpdfComponent.php

<?php
class MpdfComponent extends Component {

}
Notice: If you want to customize this error message, create app\View\Errors\missing_component.ctp

**Comment by segy** [comment]
I am sorry, but I do not have time to create demo app... this project is slightly unmaintained now :)

I'm not sure what you did - you should copy the contents of this repo to the folder Plugin\Mpdf so it is not possible that class Plugin\Mpdf\Controller\Component\MpdfComponent.php does not exist.

One more tip. I would suggest trying https://github.com/FriendsOfCake/CakePdf. They maintain it and have good readme. Good luck.
