### ISSUE TITLE
Declaration of MpdfComponent::shutdown()

### ISSUE THREAD

**Issue by egpierro** [segy/Mpdf#7]
### Using CakePHP 2x

If you have debug set to 2 on core.php, the component will fail rendering the PDF inline because of a STRICT error on the declaration of shutdown as follows:

```
Strict (2048): Declaration of MpdfComponent::shutdown() should be compatible with Component::shutdown(Controller $controller) [APP/Plugin/Mpdf/Controller/Component/MpdfComponent.php, line 119]
```

As such, the fix for this issue is to edit **line 89** of the MpdfComponent.php file to this:

```
//Add the word Controller before $controller
public function shutdown(Controller $controller) {
```

Can you please make this change, and commit?

Thanks!

Eduardo

**Comment by agrohelp** [comment]
After moving from localhost to a remote server I have the same problem. The problem I can not solve. Yours.

**Comment by segy** [comment]
changed. thanks for suggestion
